# -*- coding: utf-8 -*-
"""ui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIn0QfKIPNG9emDIy_pSnbcAFbYA4NVV
"""

!pip install streamlit
import streamlit as st

st.set_page_config(page_title="FaceAuth", page_icon="🛡️")

st.title("🛡️ Biometric Security System")
st.markdown("---")
st.write("Please use the sidebar to either **Register** as a new user or **Login** to the system.")

st.sidebar.success("Select a Page above")

import streamlit as st
import subprocess

st.title("📝 User Registration")

username = st.text_input("Enter your name:")

if st.button("Start Camera for Registration"):
    if username:
        st.info(f"Capturing images for {username}... Please look at the camera.")

        subprocess.run(["python", "src/data_collection.py", "--name", username])

        st.success("Registration images saved successfully!")
    else:
        st.error("Please enter a name first.")

import streamlit as st
import subprocess

st.title("🔐 System Login")

if st.button("Scan Face to Login"):
    st.warning("System is scanning... please wait.")

    result = subprocess.check_output(["python", "src/predict.py"], text=True)

    if "Access Granted" in result:
        st.success(f"🔓 {result}")
        st.balloons()
    else:
        st.error(f"🚫 {result}")

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Aash77-b/Face-Auth.git
# %cd Face-Auth

!git config --global user.email "aash7t@gmail.com"
!git config --global user.name "Aash77-b"

!cp /content/ui.ipynb /content/Face-Auth/

